# Generated by Django 3.0.6 on 2020-07-17 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200717_0950'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PizzaSetOrder',
        ),
    ]
