# Generated by Django 3.0.6 on 2020-07-17 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_delete_pizzasetorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaSetOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppings', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=30)),
                ('count', models.IntegerField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Dish')),
            ],
        ),
    ]
